### ISSUE TITLE
Using EWSMA 2.0 with SQL Server CLR

### ISSUE THREAD

**Issue by johnjarrard** [OfficeDev/ews-managed-api#101]
I have loaded  the Microsoft.Exchange.WebServices.dll file into my SQL Server 2016 (connecting to an exchange server 2010) and am hoping to use this API as a means to query the exchange server. 

Everything compiles fine, but when I execute it, I get this runtime error:

```
Msg 6522, Level 16, State 1, Line 4
A .NET Framework error occurred during execution of user-defined routine or aggregate "EXT_ExchangeCalendar": 
System.TypeInitializationException: The type initializer for 'Microsoft.Exchange.WebServices.Data.ExchangeServiceBase' threw an exception. ---> System.ArgumentException: The path is not of a legal form.
System.ArgumentException: 
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetFullPathWithAssert(String fileName)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Microsoft.Exchange.WebServices.Data.EwsUtilities.<.cctor>b__9()
   at Microsoft.Exchange.WebServices.Data.LazyMember`1.get_Member()
   at Microsoft.Exchange.WebServices.Data.ExchangeServiceBase..cctor()
System.TypeInitializationException: 
   at Microsoft.Exchange.WebServices.Data.ExchangeServiceBase..ctor(TimeZoneInfo timeZone)
   at UserDefinedFunctions.EXT_ExchangeCalendar(DateTime startdate, DateTime enddate, String username, String password, String domain, String url)
```
.

The Error doesn't show up when I run the same code as  console application.  My best is that it has to do with SQL server not being able to load the Microsoft.Exchange.WebServers.Auth.dll file.

**Comment by poizan42** [comment]
The issue is at this line: https://github.com/OfficeDev/ews-managed-api/blob/154dbc66ac018d861c73ce489839cd9f58a1b0cd/Core/EwsUtilities.cs#L66

Location on an assembly isn't reliable and can't be expected to work in hosting scenarios or just inside another AppDomain. EscapedCodebase should be used to determine the location (which may not actually be a local file url!)

The file version resource could in principle be read directly from the module in memory, but there isn't any framework support for this. But this seems silly anyways since the managed file version from Assembly.GetName().Version should contain the same value anyways unless it gets customized by linking the final assembly with cl/link, which I doubt is the case.

**Comment by poizan42** [comment]
Also note that this has a fallback added in 45459165001657f3db7d92d094b960d3abec390f, so presumably you are using a version predating this
