### ISSUE TITLE
Localized strings are not building correctly, exception thrown

### ISSUE THREAD

**Issue by i68040** [OfficeDev/ews-managed-api#19]
After I compile the Microsoft.Exchange.WebServices.Data solution and use it in a project I get the following exception when base.GetString is called in ExchangeResourceManager.cs line 122:

System.Resources.MissingManifestResourceException was unhandled
  HResult=-2146233038
  Message=Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Exchange.WebServices.Strings.resources" was correctly embedded or linked into assembly "Microsoft.Exchange.WebServices.Data" at compile time, or that all the satellite assemblies required are loadable and fully signed.
  Source=mscorlib
  StackTrace:
       at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
       at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
       at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
       at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
       at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
       at Microsoft.Exchange.WebServices.Data.ExchangeResourceManager.GetString(String name, CultureInfo culture) in c:\Repos\Microsoft\EWS-Managed-API\ResourceManager\ExchangeResourceManager.cs:line 122
       at Microsoft.Exchange.WebServices.Data.LocalizedString.System.IFormattable.ToString(String format, IFormatProvider formatProvider) in c:\Repos\Microsoft\EWS-Managed-API\ResourceManager\LocalizedString.cs:line 435
       at Microsoft.Exchange.WebServices.Data.LocalizedString.ToString() in c:\Repos\Microsoft\EWS-Managed-API\ResourceManager\LocalizedString.cs:line 382
       at Microsoft.Exchange.WebServices.Data.LocalizedString.op_Implicit(LocalizedString value) in c:\Repos\Microsoft\EWS-Managed-API\ResourceManager\LocalizedString.cs:line 135
       at Microsoft.Exchange.WebServices.Data.ExchangeService.DefaultAutodiscoverRedirectionUrlValidationCallback(String redirectionUrl) in c:\Repos\Microsoft\EWS-Managed-API\Core\ExchangeService.cs:line 4431
       at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.CallRedirectionUrlValidationCallback(String redirectionUrl) in c:\Repos\Microsoft\EWS-Managed-API\Autodiscover\AutodiscoverService.cs:line 1504
       at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetSettings[TGetSettingsResponseCollection,TSettingName](List`1 identities, List`1 settings, Nullable`1 requestedVersion, GetSettingsMethod`2 getSettingsMethod, Func`1 getDomainMethod) in c:\Repos\Microsoft\EWS-Managed-API\Autodiscover\AutodiscoverService.cs:line 1003
       at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetUserSettings(List`1 smtpAddresses, List`1 settings) in c:\Repos\Microsoft\EWS-Managed-API\Autodiscover\AutodiscoverService.cs:line 878
       at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetSoapUserSettings(String smtpAddress, List`1 requestedSettings) in c:\Repos\Microsoft\EWS-Managed-API\Autodiscover\AutodiscoverService.cs:line 829
       at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetUserSettings(String userSmtpAddress, UserSettingName[] userSettingNames) in c:\Repos\Microsoft\EWS-Managed-API\Autodiscover\AutodiscoverService.cs:line 1667
       at Microsoft.Exchange.WebServices.Data.ExchangeService.GetAutodiscoverUrl(String emailAddress, ExchangeVersion requestedServerVersion, AutodiscoverRedirectionUrlValidationCallback validateRedirectionUrlCallback) in c:\Repos\Microsoft\EWS-Managed-API\Core\ExchangeService.cs:line 4529
       at Microsoft.Exchange.WebServices.Data.ExchangeService.AutodiscoverUrl(String emailAddress, AutodiscoverRedirectionUrlValidationCallback validateRedirectionUrlCallback) in c:\Repos\Microsoft\EWS-Managed-API\Core\ExchangeService.cs:line 4458
       at Microsoft.Exchange.WebServices.Data.ExchangeService.AutodiscoverUrl(String emailAddress) in c:\Repos\Microsoft\EWS-Managed-API\Core\ExchangeService.cs:line 4441
       at MyApp.Program.Main(String[] args) in c:\Users\rc185201\Documents\Visual Studio 2013\Projects\MyApp\MyApp\Program.cs:line 19
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by jvanna** [comment]
Hi, Am facing few issues with Resources.resx file. I have added this file in properties and able to see the same in my ewsmanagedapi project. but still am getting error like below:

Error	1	<Base path>ews-managed-api-master\Properties\Resources.resx' is not a valid Win32 resource file	<Base path>ews-managed-api-master\CSC	Microsoft.Exchange.WebServices.Data

let me know, how to resolve this issue.

**Comment by dclaux** [comment]
Hi there, we are going to simply remove the need for a resx file in the API, and instead use a set of static strings. The change is here: https://github.com/OfficeDev/ews-managed-api/pull/24
