### ISSUE TITLE
Out of memory exception - Large XML 

### ISSUE THREAD

**Issue by fsforna** [OfficeDev/ews-managed-api#60]
Dear All,
during a Exchange extraction process we encountered an exception due to out of memory. An Exchange mail item has some attachments and the total amount of attachments is 112Mb. 
Have you ever faced this kind of issue?

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.set_Length(Int32 value)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlCharCheckingReader.Read()
   at Microsoft.Exchange.WebServices.Data.EwsXmlReader.Read() in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\EwsXmlReader.cs:line 157

Best Regards,
Francesco.

**Comment by sabariramesh** [comment]
I am facing same issue. Your help would be greatly appreciated.
