### ISSUE TITLE
Time zones that stopped obvserving DST fail on the server

### ISSUE THREAD

**Issue by gbusbyMS** [OfficeDev/ews-managed-api#74]
It looks like the code here: https://github.com/OfficeDev/ews-managed-api/blob/master/ComplexProperties/TimeZones/TimeZoneDefinition.cs#L174 produces data that the server rejects with an error like the below. Using the following time zones as start/end time zones for a meeting will repro the issue:
            var timezone = TimeZoneInfo.FindSystemTimeZoneById("Egypt Standard Time");
            var timezone = TimeZoneInfo.FindSystemTimeZoneById("Arabic Standard Time");

Error returned by server:
ServiceResponseException thrown, result code: ErrorTimeZone, errorMessage: A referenced period is missing., Microsoft.Exchange.Services.Core.Types.TimeZoneException: A referenced period is missing.

   at Microsoft.Exchange.Services.Core.Types.TimeZoneDefinitionType.AddRuleToRuleGroup(ExTimeZoneRuleGroup timeZoneRuleGroup, TransitionType transitionToPeriod, TransitionType transitionFromPeriod, ArrayOfTransitionsType transitionToGroup)

   at Microsoft.Exchange.Services.Core.Types.TimeZoneDefinitionType.AddRulesToRuleGroup(ExTimeZoneRuleGroup timeZoneRuleGroup, TransitionType transition, ArrayOfTransitionsType transitions)

   at Microsoft.Exchange.Services.Core.Types.TimeZoneDefinitionType.ConvertToExTimeZone()

   at Microsoft.Exchange.Services.Core.DataConverter.TimeZoneProperty.SetProperty(CalendarItemBase calendarItemBase, TimeZoneDefinitionType timeZone)

   at Microsoft.Exchange.Services.Core.DataConverter.XsoDataConverter.SetProperties(StoreObject storeObject, ServiceObject serviceObject, IdConverter idConverter)

   at Microsoft.Exchange.Services.Core.ServiceCommandBase.SetProperties(StoreObject storeObject, ServiceObject serviceObject)

   at Microsoft.Exchange.Services.Core.CreateItem.UpdateNewItem(Item xsoItem, ItemType serviceObject)

   at Microsoft.Exchange.Services.Core.CreateItem.CreateStoreItem(ItemType item, ServiceError& warning)

   at Microsoft.Exchange.Services.Core.CreateItem.CreateItemFromServiceObject(ItemType item, ServiceError& warning)

   at Microsoft.Exchange.Services.Core.CreateItem.Execute()

   at Microsoft.Exchange.Services.Core.ExceptionHandler`1.Execute(CreateServiceResult createServiceResult, Int32 index, GenerateMessageXmlForServiceError generateErrorXml)

**Comment by lobastov** [comment]
There is a simple workaround for this particular case: use custom timezone without adjustment rules.
```
var tz = TimeZoneInfo.FindSystemTimeZoneById("Egypt Standard Time"); // or any other timezone that ignores DST
var lastRule = tz.GetAdjustmentRules().LastOrDefault();
if (lastRule != null && lastRule.DateEnd < DateTime.MaxValue.Date)
{
    tz = TimeZoneInfo.CreateCustomTimeZone(tz.Id, tz.BaseUtcOffset, tz.DisplayName, tz.StandardName);
}
```

**Comment by tjmoore** [comment]
For the workaround, this should be more comprehensive as makes more sense to look for any with DateEnd before now not just matching MaxValue for future adjustments, plus some tz have no adjustment rules.

```csharp
var tz = TimeZoneInfo.FindSystemTimeZoneById("Egypt Standard Time"); // or any other timezone that ignores DST
var lastRule = tzInfo.GetAdjustmentRules().LastOrDefault();
if (lastRule == null || (lastRule != null && lastRule.DateEnd.ToUniversalTime() < DateTime.UtcNow))
{
    tzInfo = TimeZoneInfo.CreateCustomTimeZone(tzInfo.Id, tzInfo.BaseUtcOffset, tzInfo.DisplayName, tzInfo.StandardName);
}
```
