### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by rdzidziguri** [OfficeDev/ews-managed-api#88]
I have a local monitoring system which monitors Exchange for meetings and displays appropriate information, but some requests fail with the following error "An item with the same key has already been added"

it happens randomly so there is not particular case when this thing will throw exception but it throws in about 30% of all calls.

i installed latest nuget package in hope that this would be resolved, but it is still presented.

**Comment by cklam2** [comment]
May be the same issue as #45. If that's the case then you'd need to wait for a new nuget package to be released.

**Comment by rdzidziguri** [comment]
any info on when it will be released?

**Comment by cklam2** [comment]
Nope, we're all waiting for Microsoft to release a new version. All you can do is leave a +1 in this post: #58 but I doubt that it's useful. 

Alternative is to download the source and build your own DLL. Though I don't know whether the license agreement allows you to do so.

**Comment by cklam2** [comment]
The issue occurred again with the fix from #45. 

Checked the code many times but could not find out why. Therefore reverted back to original code again and added throw Exception with additional info when it catches an ArgumentException. What I then saw is something that I couldn't believe. After some crunching I think I understand why this is happening. 

This is the modified code for debugging purposes (based on original version):
```
private void SaveHttpResponseHeaders(WebHeaderCollection headers)
{
    this.httpResponseHeaders.Clear();

    foreach (string key in headers.AllKeys)
    {
        try
        {
            this.httpResponseHeaders.Add(key, headers[key]);
        }
        catch (ArgumentException ae)
        {
            string s = string.Format("Duplicate: header: '{0}'='{1}', respkeys({2})=[{3}], hdrkeys({4})=[{5}]", 
                key, headers[key], 
                httpResponseHeaders.Count, string.Join(",", httpResponseHeaders.Keys.Select(s1 => "'" + s1 + "'")), 
                headers.Count, string.Join(",", headers.AllKeys.Select(s2 => "'" + s2 + "'")));
            throw new Exception(s, ae);
        }
    }

    if (this.OnResponseHeadersCaptured != null)
    {
        this.OnResponseHeadersCaptured(headers);
    }
}
```

And here the output of the exception:
```
System.Exception: Duplicate: header: 'Persistent-Auth'='true', respkeys(9)=['Transfer-Encoding','Transfer-Encoding','Persistent-Auth','Cache-Control','Content-Type','Date','Server','X-AspNet-Version','X-Powered-By'], hdrkeys(8)=['Transfer-Encoding','Persistent-Auth','Cache-Control','Content-Type','Date','Server','X-AspNet-Version','X-Powered-By'] ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.Exchange.WebServices.Data.ExchangeServiceBase.SaveHttpResponseHeaders(WebHeaderCollection headers)
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.WebServices.Data.ExchangeServiceBase.SaveHttpResponseHeaders(WebHeaderCollection headers)
   at Microsoft.Exchange.WebServices.Data.ExchangeServiceBase.ProcessHttpResponseHeaders(TraceFlags traceType, IEwsHttpWebResponse response)
   at Microsoft.Exchange.WebServices.Data.SimpleServiceRequestBase.ReadResponse(IEwsHttpWebResponse response)
   at Microsoft.Exchange.WebServices.Data.MultiResponseServiceRequest`1.Execute()
   at Microsoft.Exchange.WebServices.Data.ExchangeService.ResolveName(String nameToResolve, IEnumerable`1 parentFolderIds, ResolveNameSearchLocation searchScope, Boolean returnContactDetails, PropertySet contactDataPropertySet)
   at Test.Exchange.Internal.Session.RunTask(Task task)
```

As you can see from the output is that the code is trying to add key 'Persistent-Auth' which is already in the collection so an ArgumentException is thrown. And in the respkeys (=all keys from httpResponseHeaders) there are already duplicate keys ('Transfer-Encoding'). Looking at the keys from the headers there are only 8 keys but in the respkeys there are 9!

How is this possible??? The httpResponseHeaders is cleared at the start. Therefore the only logical explanation I could think of is that the httpResponseHeaders is accessed simultaneously by 2 threads. But still can't explain why the Dictionary can store 2 duplicate keys.

**Comment by cklam2** [comment]
Proposed solution is protecting the field by using a lock object. See [this commit](https://github.com/cklam2/ews-managed-api/commit/e554317a85401303ff845dcbe129fce832d43429). Did not yet create a pull request, need to verify whether solution works as expected.

Note that the 'this.httpResponseHeaders' is only filled and not used elsewhere in the entire code base (property `HttpResponseHeaders` has 0 references) so alternative solution is to remove the entire `SaveHttpResponseHeaders` but that may be a bit too drastic.

**Comment by georgecheyne** [comment]
Hi,

Just a further comment on this.

I have some code that is getting this error and then trying to resend the email object because it detected an issue.  Obviously as this is in deserialising the response from exchange the email has been sent correctly so my retries would be an issue.

However on doing the retries I'm seeing this error:
System.ArgumentException: Stream was not readable.
   at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at Microsoft.Exchange.WebServices.Data.EwsServiceXmlWriter.WriteBase64ElementValue(Stream stream) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\EwsServiceXmlWriter.cs:line 389
   at Microsoft.Exchange.WebServices.Data.FileAttachment.WriteElementsToXml(EwsServiceXmlWriter writer) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\ComplexProperties\FileAttachment.cs:line 205
   at Microsoft.Exchange.WebServices.Data.ComplexProperty.WriteToXml(EwsServiceXmlWriter writer, XmlNamespace xmlNamespace, String xmlElementName) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\ComplexProperties\ComplexProperty.cs:line 273
   at Microsoft.Exchange.WebServices.Data.ComplexPropertyCollection`1.WriteElementsToXml(EwsServiceXmlWriter writer) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\ComplexProperties\ComplexPropertyCollection.cs:line 309
   at Microsoft.Exchange.WebServices.Data.ComplexProperty.WriteToXml(EwsServiceXmlWriter writer, XmlNamespace xmlNamespace, String xmlElementName) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\ComplexProperties\ComplexProperty.cs:line 273
   at Microsoft.Exchange.WebServices.Data.ComplexPropertyDefinitionBase.WritePropertyValueToXml(EwsServiceXmlWriter writer, PropertyBag propertyBag, Boolean isUpdateOperation) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\PropertyDefinitions\ComplexPropertyDefinitionBase.cs:line 222
   at Microsoft.Exchange.WebServices.Data.PropertyBag.WriteToXml(EwsServiceXmlWriter writer) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\PropertyBag.cs:line 688
   at Microsoft.Exchange.WebServices.Data.CreateRequest`2.WriteElementsToXml(EwsServiceXmlWriter writer) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\CreateRequest.cs:line 86
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.WriteBodyToXml(EwsServiceXmlWriter writer) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\ServiceRequestBase.cs:line 160
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.WriteToXml(EwsServiceXmlWriter writer) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\ServiceRequestBase.cs:line 303
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.EmitRequest(IEwsHttpWebRequest request) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\ServiceRequestBase.cs:line 419
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.BuildEwsHttpWebRequest() in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\ServiceRequestBase.cs:line 793
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.ValidateAndEmitRequest(IEwsHttpWebRequest& request) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\ServiceRequestBase.cs:line 687
   at Microsoft.Exchange.WebServices.Data.ExchangeService.InternalCreateItems(IEnumerable`1 items, FolderId parentFolderId, Nullable`1 messageDisposition, Nullable`1 sendInvitationsMode, ServiceErrorHandling errorHandling) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\ExchangeService.cs:line 396
   at Microsoft.Exchange.WebServices.Data.Item.InternalCreate(FolderId parentFolderId, Nullable`1 messageDisposition, Nullable`1 sendInvitationsMode) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\ServiceObjects\Items\Item.cs:line 200
   at Microsoft.Exchange.WebServices.Data.EmailMessage.InternalSend(FolderId parentFolderId, MessageDisposition messageDisposition) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\ServiceObjects\Items\EmailMessage.cs:line 110
   at Microsoft.Exchange.WebServices.Data.EmailMessage.SendAndSaveCopy() in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\ServiceObjects\Items\EmailMessage.cs:line 248

It looks like it's having an issue trying to read the stream that holds the attachments on subsequent attempts to send the same EmailMessage object.

This is lucky for me or I would be resending the email loads of times but may cause an issue for someone else.  I guess the stream should be reset to position zero after being read or something.

Just thought I'd add in case anyone is thinking of fixing this bug.

**Comment by zuckerthoben** [comment]
I have the same issue, I also have the same use case. Here is the stack trace: 

An item with the same key has already been added. , StackTrace: at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at Microsoft.Exchange.WebServices.Data.ExchangeServiceBase.SaveHttpResponseHeaders(WebHeaderCollection headers) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\ExchangeServiceBase.cs:line 340 at Microsoft.Exchange.WebServices.Data.SimpleServiceRequestBase.ReadResponse(IEwsHttpWebResponse response) in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\SimpleServiceRequestBase.cs:line 111 at Microsoft.Exchange.WebServices.Data.MultiResponseServiceRequest`1.Execute() in \\REDMOND\EXCHANGE\BUILD\E15\15.00.0913.015\SOURCES\sources\dev\EwsManagedApi\src\EwsManagedApi\Core\Requests\MultiResponseServiceRequest.cs:line 157 at OfficeApi.Helpers.ExchangeHelper.GetAllAppointmentsFromEmailAddress(String roomEmailAddress, DateTime endDate)

And here is my code where the error occurs:

    public static List<Appointment> GetAllAppointmentsFromEmailAddress(string roomEmailAddress, DateTime endDate)
        {
            var startDate = DateTime.Now;
            var cView = new CalendarView(startDate, endDate, NUMAPPTS);
            var folderId = new FolderId(WellKnownFolderName.Calendar, roomEmailAddress);

            var appointments = ExService.FindAppointments(folderId, cView).ToList();

            foreach (var appointment in appointments)
            {
                appointment.Load(new PropertySet
                {
                    ItemSchema.Id,
                    ItemSchema.LastModifiedTime,
                    ItemSchema.Subject,
                    ItemSchema.DisplayTo,
                    ItemSchema.DisplayCc,
                    AppointmentSchema.IsMeeting,
                    AppointmentSchema.Organizer,
                    AppointmentSchema.Start,
                    AppointmentSchema.End,
                    AppointmentSchema.RequiredAttendees,
                    AppointmentSchema.OptionalAttendees,
                    AppointmentSchema.Location,
                    AppointmentSchema.Resources,
                    AppointmentSchema.LegacyFreeBusyStatus,
                    AppointmentSchema.IsCancelled,
                });
            }

            return appointments;
        }

How can I workaround the bug?

**Comment by cklam2** [comment]
I know it's super late for a solution but Microsoft just stated (see #104) that this happens when you access the same EWS instance from multiple threads. Solution is to create an instance per thread.
